export const UNAUTHORIZED_STATUS = 401;
export const BAD_REQUEST_STATUS = 400;
export const NOT_FOUND_STATUS = 404;
export const FORBIDDEN_STATUS = 403;
export const SERVICE_UNAVAILABLE_STATUS = 503;
export const SERVER_INTERNAL_ERROR_STATUS = 500;